### PR TITLE
Unsafe gram

### PR DESCRIPTION
**Pull request by vincentcp**
Adds Haar basis and AbstractMeasure to ensure more robust inner products.

### CODE REVIEW

**Comment by vincentcp** [comment]
I made a more clear distinction between `Measure` and `DiscreteMeasure` to avoid bugs in the future. Both are `AbstractMeasure`s now.

**Comment by vincentcp** [comment]
Fixes #6

**Comment by daanhb** [comment]
Strictly speaking the name Haar function corresponds to the wavelet, not the block function itself. Perhaps the example basis can be named PiecewiseConstants?

**Comment by daanhb** [comment]
Looks good!

**Pull request merged**
